version: "3.8"
services:
  app:
    image: node:16.13.2
    volumes:
      - type: bind
        source: .
        target: /usr/src/service
      - type: volume
        source: node_modules
        target: /usr/src/service/node_modules
        volume:
          nocopy: true
    working_dir: /usr/src/service
    ports:
      - '8080:8080'
    tty: true
volumes:
  node_modules:
